### ISSUE TITLE
SCP Task

### ISSUE THREAD

**Issue by DavidSporer** [TYPO3/Surf#10]
Hi,

I've created an SCP Task for the flow-based version of Surf.
https://gist.github.com/DavidSporer/7485da2e83421cb06292

Does it make sense to include this to the core of this new version or is it something that most people don't need?

Regards,
David

**Comment by oliverklee** [comment]
:+1:

**Comment by helhum** [comment]
Cool! Feel free to create a pull request. Don't forget to add tests for the task and to introduce it as new transfer method

**Comment by simonschaufi** [comment]
Done with #215
