### ISSUE TITLE
optionally remove composer.lock

### ISSUE THREAD

**Issue by DanielRuf** [TYPO3/Surf#100]
I'm not sure if there was an option added. So far the lock file in the surf deployment / cache directory is not automatically deleted when not using one. This prevents automatic dependency updates for some projects.

So far we have to add another custom task which does this step.

**Comment by t3easy** [comment]
You can force git to reset the workspace: `$application->setOption('TYPO3\\Surf\\Task\\Package\\GitTask[hardClean]', true);`
Or add a task that deletes the file after clone.

**Comment by DanielRuf** [comment]
The lockfile is often committed. A predefined task for doing this might be useful in some cases.

**Comment by t3easy** [comment]
But if you commit it, why would you not wanna use it?

**Comment by t3easy** [comment]
Or maybe use `gitPostCheckoutCommands`
https://github.com/TYPO3/Surf/blob/8f05ab2193a7d64aa4c25bd135c19d7fd2cce6a6/src/Task/Git/AbstractCheckoutTask.php#L120-L139

**Comment by DanielRuf** [comment]
> But if you commit it, why would you not wanna use it?

It was just an example. So far composer automatically generated a lockfile.

**Comment by DanielRuf** [comment]
> Or maybe use gitPostCheckoutCommands

Sure. We already have our custom task for doing this but my feature request was to have such a task available as part of the predefined Surf task. For me it makes sense.

Or what do you mean? Should everyone implement a different solution for the same problem?

**Comment by DanielRuf** [comment]
If it is needed more than once (writing this custom task) why not provide a predefined task? Siplification by design and better DX for "users".

**Comment by kaystrobach** [comment]
@DanielRuf i would happily guide you doing it - what do you think? Should we start a PR together?

**Comment by sabbelasichon** [comment]
@kaystrobach @DanielRuf: Did you talk about this issue together? Would be nice to see a PR.

**Comment by DanielRuf** [comment]
> @kaystrobach @DanielRuf: Did you talk about this issue together? Would be nice to see a PR.

Not yet. Had no time so far and totally forgot about this one here, sorry.

How can we proceed here?

> @DanielRuf i would happily guide you doing it - what do you think? Should we start a PR together?

This would be helpful and sounds good.

**Comment by t3easy** [comment]
@DanielRuf As an idea: instead of remove the composer.lock, running `composer update` after the `composer install` task will have the same effect with the pro that you can see which packages are updated. The only con is the time for download.

**Comment by sabbelasichon** [comment]
I am going to close this issue. Feel free to reopen it.
