### ISSUE TITLE
RsyncTask ignores excludes if custom flags are set

### ISSUE THREAD

**Issue by skdmind** [TYPO3/Surf#101]
If you set rsync flags(in my case I needed --append-verify) it will ignore all rsync excludes you've set.

in case this isn't intended:

in TYPO3\Surf\Task\Transfer\RsyncTask:execute():
`$rsyncFlags = isset($options['rsyncFlags']) ? $options['rsyncFlags'] : '--recursive --times --perms --links --delete --delete-excluded' . $excludeFlags;`
to:
`$rsyncFlags = (isset($options['rsyncFlags']) ? $options['rsyncFlags'] : '--recursive --times --perms --links --delete --delete-excluded') . $excludeFlags;`

**Comment by t3easy** [comment]
@skdmind would you like to review and Approve #115?

**Comment by skdmind** [comment]
@t3easy thanks a lot, works completely fine for me
