### ISSUE TITLE
Remove dependency to neos/utility-files

### ISSUE THREAD

**Issue by georgringer** [TYPO3/Surf#103]
Only one method of `neos/utility-files` is used and that is `concatenatePaths` which again just uses  1 other method.

Would be good to use own code to remove that dependency.

**Comment by sabbelasichon** [comment]
Really would like to get rid of dependencies. But we use externally one other method from neos/utility-files `readDirectoryRecursively` which again uses another method and this also another one.

We could just copy these 4-5 methods to some Util class and get rid of the dependency. 
Do you think this is worth it?

**Comment by kitsunet** [comment]
Do what you want, but that's what dependency management is for. Doesn't need to be as extreme as in node, but I don't see a good reason why you would copy any code?

**Comment by Sebobo** [comment]
The question is, how would it help us right now?
We don't solve a real problem with removing the dependency and we have to maintain more code. If it would be one tiny function, sure, but as you say it's several methods. And I remember at the time, Helmut was quite happy to have some small library functions he could use when he rewrote Surf.

**Comment by sabbelasichon** [comment]
I totally agree. So i am going to close this issue. Anyways thanks for opening this issue.

**Comment by dr2okevin** [comment]
I'm currelntly updating a Flow application to version 4. The Deployment uses Surf and as far as I can see surf needs to be updatet do 2.0.0-beta8 or newer. Flow Requires neos/utility-files 4.* but Surf wants neos/utility-files 3.*
And so, composer says "Your requirements could not be resolved to an installable set of packages."

**Comment by kaystrobach** [comment]
use surf.phar, don't mix the dependencies, or you will always loose 😄

**Comment by kaystrobach** [comment]
or if you really want to install surf via composer create a Build/surf folder, create a composer.json for surf there and have it's dependencies managed independently
