### ISSUE TITLE
Provide issue template

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#108]
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by t3easy** [comment]
Looks not suitable for Surf to me.
I would remove the `Example Project` part and add questions about `Surf Version`, `PHP Version`, `Environment (CI)`, `deployment configuration`. Maybe like https://github.com/TYPO3-Console/TYPO3-Console/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by sabbelasichon** [comment]
@t3easy I did a pull request #121  regarding this issue.

**Comment by t3easy** [comment]
@sabbelasichon Thx, I've seen it, but had no time to think about ;)
