### ISSUE TITLE
Think about quality assurance task with phpqa ...

### ISSUE THREAD

**Issue by kaystrobach** [TYPO3/Surf#109]
maybe it makes sense to have several profiles which allow to run several types of tasks:

* build
* test
* qa (static code analysis)
* deploy

**Comment by simonschaufi** [comment]
you are free to add as many other own steps as you like

**Comment by kaystrobach** [comment]
sure, just collecting opinions ... if so i would implement it as task ...

**Comment by simonschaufi** [comment]
in my opinion code analysis is more about continuous integration, not about deployment.

**Comment by masi** [comment]
-  static code analysis
-  build
-  test
-  deploy
 
As PHP is interpretive a simple liniting of all PHP files prior to building would ensure that a broken file slips through if test coverage is less than 100%.

npm boasts its newewst version can find security issues in JS code by doing static analysis. Something like that could make sense to check for before deploying. But there is the risk of false positives.

**Comment by sabbelasichon** [comment]
i am going to close this issue. This is in my opinion not part of the surf at the moment.
