### ISSUE TITLE
Revert symlink array change

### ISSUE THREAD

**Issue by astehlik** [TYPO3/Surf#11]
Can db5c9d17eb1a4bd2e0eceb9af25df3136bfc5761 please be reverted? It causes some problems:

1. The [BaseApplication::addSymlink()](https://github.com/TYPO3/Surf/blob/master/src/Application/BaseApplication.php#L143) method still uses the other order and creates the symlink array with wrong array keys / values.
2. It might occur that you have multiple symlinks to the same file. This can not be provided in the array because the source path can only occur once:

```php
$array = (
  'index.php' => 'typo3_src/index.php'
  'otherpath/index.php' => 'typo3_src/index.php'
);
```

**Comment by helhum** [comment]
OK, makes sense. Sorry for the inconvenience

**Comment by helhum** [comment]
fixed
