### ISSUE TITLE
Add Task, which add information about the release on the node

### ISSUE THREAD

**Issue by kaystrobach** [TYPO3/Surf#112]
Can be:

* last deployment
* who deployed
* last commits / commit messages
* identifier (git head sha?)

This would make it possible to clearly communicate this stuff inside the application.

**Comment by Sebobo** [comment]
This would be helpful for several things. I'm currently using sentry for logging and having a standardized file from which I could read the current release and attach it to error logs would be quite cool.

**Comment by sabbelasichon** [comment]
@kaystrobach do you have suggestions for the following questions:

- Where would you place the file?
- What is the name of the file?
- How to get the information who deployed?

**Comment by kaystrobach** [comment]
i would recommend having a release file in the root of the directory

so like `releases/2018xxxx/.surf/release.json

The file should contain:

* vcs
  * tag
  * branch
  * HEAD commit
  * git log as diff to deployment before (optional)
* deployment
  * identifier
  * date
  * who deployed
* other information

maybe it makes sense to define a json schema?

**Comment by kaystrobach** [comment]
naming of the file should take care of

* https://github.com/Carthage/Carthage/blob/master/Documentation/VersionFile.md

I thought there was a VERSION file standard, but i can't find it right now.

**Comment by simonschaufi** [comment]
@kaystrobach 

> who deployed

Who is this "who"? The system user that started the surf process? The git user?

**Comment by kaystrobach** [comment]
can't we use php here? most of the stuff (except the git specific) is easily available in php.

**Comment by kaystrobach** [comment]
who: the user who started surf or a separated user which is passed via ENV

**Comment by Sebobo** [comment]
I now write my Gitlab `CI_COMMIT_TAG` with a custom shell task into the `.env` file, assign it to `FLOW_RELEASE` and use it anywhere I need it.

**Comment by simonschaufi** [comment]
@Sebobo I'm thinking about a use case and the only one that comes to my mind is something like Sentry?

**Comment by sabbelasichon** [comment]
Feel free to reopen.
