### ISSUE TITLE
[IDEA] optimize deployment speed for gitlab

### ISSUE THREAD

**Issue by kaystrobach** [TYPO3/Surf#113]
Currently most projects (for me work like that)

* do composer install in other task already
* launch gitlab runner
  * git checkout
  * apply runner caches
* launch surf
  * git checkout **again** in subfolder
  * do composer install **again** 
  * deploy

So maybe it makes sense to have another strategy for getting the code (local file system instead of git). This would eliminate the doubled composer install runs.

**Comment by kaystrobach** [comment]
Agree, anyway a composer install on a completely cache version is very fast 😉

caches are restored by gitlab automatically and artifacts are passed from stage to stage

**Comment by t3easy** [comment]
And if you also cache the composer cache with GitLab, you can already speed up your current Surf deployment a lot, because the composer command fired by Surf also use it 😉

**Comment by straschek-io** [comment]
You could just skip the git checkout and add the [LocalInstallTask](https://github.com/TYPO3/Surf/blob/master/src/Application/BaseApplication.php#L217) (which triggers [Composer/InstallTask](https://github.com/TYPO3/Surf/blob/master/src/Task/Composer/InstallTask.php)) manually:
https://gist.github.com/straschek-io/66af03e5be9df3cf5ba312e16de60a10 – note that you will have to exclude build folders etc. 

Maybe it would be a cool feature to add a similar task like [Transfer/RsyncTask](https://github.com/TYPO3/Surf/blob/master/src/Task/Transfer/RsyncTask.php) w/ configurable `rsyncEcxludes` for copying the current repo to the surf workspace.

Assumption: the duplicate `composer install` may be correct in most cases, as you will likely execute some tests with `require-dev` packages and then deploy without.

**Comment by sabbelasichon** [comment]
Closed: Due to inactivity. Feel free to reopen the issue.
