### ISSUE TITLE
Ease distinction of task classes & defined tasks

### ISSUE THREAD

**Issue by straschek-io** [TYPO3/Surf#114]
It may be confusing for new users that there are FQCN-alike task names like `TYPO3\\Surf\\DefinedTask\\Composer\\LocalInstallTask` & "real" class names like [TYPO3\\Surf\\Task\\Composer\\InstallTask](https://github.com/TYPO3/Surf/blob/master/src/Task/Composer/InstallTask.php).

One first step could be to use `:class` constants whereas possible (means: when there is a distinct PHP class for a task).

**Comment by sabbelasichon** [comment]
As we now have defined PHP 5.6 as minimum requirement, we should definitely do this.
