### ISSUE TITLE
Remove support for coreapi

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#125]
Last release: 26. Jan 2016
https://extensions.typo3.org/extension/coreapi/
No support for TYPO3 >7.6

👎keep in Surf 2.0
👍remove in Surf 2.0

**Comment by kaystrobach** [comment]
anyway it can be used if you specify the commands -> so fine with that.

**Comment by t3easy** [comment]
OK no big breaking after beta status... New tasks like #80 will be typo3_console only, OK?

**Comment by sabbelasichon** [comment]
Yes.
