### ISSUE TITLE
Discuss Vision of Surf and compile a vision document

### ISSUE THREAD

**Issue by kaystrobach** [TYPO3/Surf#126]

**Comment by josefglatz** [comment]
Any updates ob this? Or blueprint anywhere online? I‘m interested ☺️

**Comment by kaystrobach** [comment]
Still working on it - currently locally, maybe next week

**Comment by sabbelasichon** [comment]
@kaystrobach Maybe you can add this to the documentation folder, so it will be part of the generated documentation itself.

**Comment by sabbelasichon** [comment]
Closed: Due to inactivity. Feel free to reopen the issue.
