### ISSUE TITLE
Update php-cs-fixer config and run it via travis

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#138]
We could update the config like https://github.com/TYPO3/TYPO3.CMS/blob/master/Build/.php_cs and run the check with travis.

**Comment by georgringer** [comment]
I would prefer to use styleci, https://github.com/georgringer/news/blob/master/.styleci.yml as it tests automatically in github as well and sends pull requests there. IMO it is easier to use and "enough" for extensions

**Comment by t3easy** [comment]
I like php-cs-fixer because you can run it local. But we could update the config to have them in place and add StyleCI as well to test PRs.
