### ISSUE TITLE
New Release (2.0.0-beta.8?)

### ISSUE THREAD

**Issue by chvonrohr** [TYPO3/Surf#148]
Last release is already more than a year old and since last release, namespaces in flow/neos have changed. Would be awesome to have a newer phar file for downloading in CD scripts...
Are there any plans?

**Comment by kaystrobach** [comment]
We are on it - you can use the latest master.

**Comment by chvonrohr** [comment]
cool - nice to hear that. 
master contains beta7 phar file, so I have to build phar my own and store it somewhere for downloading... 
but happy knowing there is a release coming in the near future..

**Comment by t3easy** [comment]
>cool - nice to hear that.  ...

@chvonrohr you can install Surf as global composer package. `composer global require typo3/surf:dev-master`
