### ISSUE TITLE
Extract Application Version (for Flow and TYPO3 from composer.json)

### ISSUE THREAD

**Issue by kaystrobach** [TYPO3/Surf#149]
## Expected Behavior

Use composer.json / composer.lock to read version and use correct Tasks automatically 

## Actual Behavior

Set manually

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Surf Version:
  - Application: 
  - PHP Version:
  - Platform:
  - Environment (CI):
  - Deployment configuration:

**Comment by sabbelasichon** [comment]
@kaystrobach Could you explain this a little bit more by example?

**Comment by sabbelasichon** [comment]
Closed: Due to inactivity. Feel free to reopen the issue.
