### ISSUE TITLE
Cycle for task "TYPO3\Surf\Task\Generic\CreateDirectoriesTask" detected

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#161]
## Expected Behavior
TYPO3\\Surf\\Task\\CreateDirectoriesTask', 'TYPO3\\Surf\\Task\\Generic\\CreateDirectoriesTask

## Actual Behavior
the task is inserted after itself
https://github.com/TYPO3/Surf/commit/d9fbe050b3bfc7f2a93cb2fcf45509e52bfa4eef#diff-d548aa5e355f8d90ca516b9c4e9b2459L102

## Steps to Reproduce the Problem

  1. run deployment with surf master

## Specifications

  - Surf Version: master
  - Application: BaseApplication and extending
  - PHP Version: all
  - Platform:
  - Environment (CI):
  - Deployment configuration:

**Comment by sabbelasichon** [comment]
i will check this and will fix it immediately.

**Comment by t3easy** [comment]
I'm already on it. you can review in a minute.

**Comment by sabbelasichon** [comment]
ok. Thanks. Would be really cool to have a real deployment the next time in form of functional testing.
