### ISSUE TITLE
Set phpBinaryPathAndFilename on target node

### ISSUE THREAD

**Issue by ochorocho** [TYPO3/Surf#176]
## Expected Behavior
Composer should use the set PHP binary in option `phpBinaryPathAndFilename` on target node
e.g. "/usr/bin/php72 composer"

This might be related to #31 

## Actual Behavior
On the target node surf runs only "composer install" without the binary path prefix
https://github.com/TYPO3/Surf/blob/master/src/Application/Neos/Flow.php#L47

## Steps to Reproduce the Problem
  1. Install custom php on target node (non default location)
  2. Run surf
  3. Composer fails during install

Output Gitlab ci
```bash
Stage update
buch.knallimall.org (Buecherei_Oberroth) TYPO3\Surf\Task\Composer\InstallTask
Loading composer repositories with package information Installing dependencies from lock file Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them. Your requirements could not be resolved to an installable set of packages.    Problem 1     - ocramius/proxy-manager 2.2.0 requires php ^7.2.0 -> your PHP version (7.1.19) does not satisfy that requirement.     - ocramius/proxy-manager 2.2.0 requires php ^7.2.0 -> your PHP version (7.1.19) does not satisfy that requirement.     - Installation request for ocramius/proxy-manager 2.2.0 -> satisfiable by ocramius/proxy-manager[2.2.0].
Got exception "Command returned non-zero return code: 2" but rollback disabled. Stopping.
```
## Specifications

  - Surf Version: latest dev-master
  - Application: Flow/Neos
  - PHP Version: 7.2
  - Platform: Linux/Ubuntu
  - Environment (CI): Gitlab CI 11

## Workaround for now

Set updateMethode to override the default composer command:

```php
$application->setOption('updateMethod', '/usr/bin/php7.2 composer');
```

For sake of consistency i would expect `phpBinaryPathAndFilename` to be used to run composer binary as it is used in every other place in surf.

**Comment by kaystrobach** [comment]
Why would you run a composer install on the target node and not in ci? Imho it’s a bad practice to have composer on the target node.

You should use composer on the ci node and then transfer the result.

**Comment by ochorocho** [comment]
Yep, you are right. But thats the way it was by default.

I'd better remove/empty the the `updateMethod` option.

**Comment by ochorocho** [comment]
@kaystrobach as i said you are right :-) ... imho, it would make sense to prefix the composer command with `phpBinaryPathAndFilename` option. For sake of consistency.

**Comment by sabbelasichon** [comment]
@ochorocho Beside the fact that @kaystrobach is right conceptually. We will do it.

**Comment by ochorocho** [comment]
Yep, works as expected. Thanks :-)
