### ISSUE TITLE
Migrate or remove encryption functionality

### ISSUE THREAD

**Issue by helhum** [TYPO3/Surf#2]
The encryption command still does not work and is bound to Flow.
We need to decide wether to remove it or migrate to symfony console command

**Comment by SomeBdyElse** [comment]
From my point of view, the encryption functionality can be removed. For automated deployments, the keys for the encrypted files need to be stored on the deployment server anyways. So I do not see a big gain in security by encrypting them. 

Or am I missing a primary use case here?

**Comment by Sebobo** [comment]
I used this feature in a project and had some trouble with switching to surf.phar because of that.
But after thinking about a solution I came to the same conclusion as @SomeBdyElse.

**Comment by kaystrobach** [comment]
👍 for removing, keys should never be stored in VCS ... and there are better more secure solutions like envs...

**Comment by hlubek** [comment]
I'm okay to remove that, there are tools now that cover this case like https://www.vaultproject.io/
