### ISSUE TITLE
WebOpcacheResetCreateScriptTask writes on localhost

### ISSUE THREAD

**Issue by Lemmork** [TYPO3/Surf#21]
Why does this script write the opcodecache file to localhost?
I think it has to be placed on remote so that I can execute it with the WebOpcacheResetExecuteTask.

**Comment by helhum** [comment]
If your transfer method is rsync, this is fine, as the locally generated file will be transferred to the target node during rsync transmission.

But I agree, this needs to be re-worked to be useable for other transfer methods as well.

**Comment by sabbelasichon** [comment]
It is actually simple to add a predefined reset file and its content with a cryptic name by yourself in your git repository and explicitly define the scriptIdentifier for the WebOpcacheResetExecuteTask. So at the moment we are not going to fix this issue here.
