### ISSUE TITLE
Set rsyncExcludes by webDirectory

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#217]
## Expected Behavior
set rsyncExcludes 'web/fileadmin', 'web/uploads' by respecting webDirectory

## Actual Behavior
webDirectory and rsyncExcludes have to be set.

## Steps to Reproduce the Problem
1.  set webDirectory to 'public'
1.  run `surf describe project`
1.  rsyncExcludes dosen't change the paths to 'public/fileadmin', 'public/uploads'

## Specifications

  - Surf Version: dev-master
  - Application: TYPO3 CMS
  - PHP Version: 7.2
  - Platform:
  - Environment (CI):
  - Deployment configuration:

**Comment by t3easy** [comment]
We could do it like https://github.com/TYPO3/Surf/blob/master/src/Task/RsyncFoldersTask.php#L63 https://github.com/TYPO3/Surf/blob/master/src/Task/RsyncFoldersTask.php#L81

**Comment by sabbelasichon** [comment]
@t3easy I think everybody has to take care of it for himself, because you can set options on different levels in surf. For example only for the application or only for the task. This would lead to change the code in different places. It is not worth the effort in my opinion. Feel free to reopen

**Comment by t3easy** [comment]
@sabbelasichon  I would introduce a `{webDirectory}`  variable which is in the default rsyncExcludes instead of `web` and process the excludes like in https://github.com/TYPO3/Surf/blob/master/src/Task/RsyncFoldersTask.php#L81
Around 10 lines of code, non breaking, more ootb, and with configuration receiver from composer.json as a possible next step.

**Comment by sabbelasichon** [comment]
@t3easy Sound good. Feel free to open an PR

**Comment by josefglatz** [comment]
Since TYPO3 9.5 LTS a fresh composer based installation of the application does use `public` as default webDirectory. This seems reason enough to add support for that?

**Comment by t3easy** [comment]
I already have a patch for that. I’ll push it the next days.

**Comment by t3easy** [comment]
@josefglatz @schreiberten Would you like to look at the branch 217? It's not very beautifully but it works.
