### ISSUE TITLE
surf.phar throws PHP Fatal error if it's read only

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#218]
## Expected Behavior
All commands except selfupdate must work if surf.phar is readonly 

## Actual Behavior
mymac:~ t3easy$ /usr/local/surf/surf.phar --version
PHP Fatal error:  Uncaught Humbug\SelfUpdate\Exception\FilesystemException: The current phar file is not writeable and cannot be replaced: /usr/local/surf/surf.phar. in phar:///usr/local/surf/surf.phar/vendor/padraic/phar-updater/src/Updater.php:430
Stack trace:
#0 phar:///usr/local/surf/surf.phar/vendor/padraic/phar-updater/src/Updater.php(101): Humbug\SelfUpdate\Updater->setLocalPharFile('/usr/local/surf...')
#1 phar:///usr/local/surf/surf.phar/src/Command/SelfUpdateCommand.php(41): Humbug\SelfUpdate\Updater->__construct(NULL, false, 'github')
#2 phar:///usr/local/surf/surf.phar/src/Integration/Factory.php(61): TYPO3\Surf\Command\SelfUpdateCommand->__construct()
#3 phar:///usr/local/surf/surf.phar/src/Cli/Symfony/ConsoleApplication.php(46): TYPO3\Surf\Integration\Factory->createCommands()
#4 phar:///usr/local/surf/surf.phar/surf(13): TYPO3\Surf\Cli\Symfony\ConsoleApplication->run()
#5 /usr/local/surf/surf.phar(10): require('phar:///usr/loc...')
#6 {main}
  thrown in phar:///usr/local/surf/surf.phar/vendor/padraic/phar-updater/src/Updater.php on line 430

## Steps to Reproduce the Problem

1. put surf in an read only location, e.g. /usr/local/surf/surf.phar like in the doc
1. run `/usr/local/surf/surf.phar --version`

## Specifications

  - Surf Version: 2.0.0-beta8
  - Application: any
  - PHP Version: any
  - Platform: mac
  - Environment (CI): no
  - Deployment configuration:

**Comment by sabbelasichon** [comment]
@t3easy Can you please test it again with the new attache surf.phar file in the release.
