### ISSUE TITLE
Task api documentation is missing in generated docs

### ISSUE THREAD

**Issue by Sebobo** [TYPO3/Surf#228]
See https://docs.typo3.org/surf/ApiReference/Task/Test/HttpTestTask.html

**Comment by sabbelasichon** [comment]
We need the sphinxcontrib.phpdomain to render the ApiReference properly, but this is at the moment not possible with the current rendering setup, we cannot do much about it:
https://github.com/t3docs/docker-render-documentation/issues/20

Nevertheless we will keep it in the documentation. At least you can see all the tasks available.
