### ISSUE TITLE
rsyncExcludes defaults for TYPO3 CMS

### ISSUE THREAD

**Issue by josefglatz** [TYPO3/Surf#246]
## Expected Behavior

Since TYPO3 v9.5 LTS: uploads folder isn't used anymore in fresh installation. Don't know if it can be used in upgraded instances.

## Actual Behavior

typo3/surf 2.0.0 beta / dev-master does always symlink the uploads folder to shared folder. (There is already an issue #217 for the thematic about a dynamic webDirectory via a variable)

## Steps to Reproduce the Problem

Fresh installation of TYPO3 9.5 LTS

## Specifications

  - Surf Version: dev-master/ 2.0.0-betaX
  - Application:  TYPO3 CMS
  - PHP Version: -
  - Platform:-
  - Environment (CI):-
  - Deployment configuration: -

**Comment by sabbelasichon** [comment]
@josefglatz This is true and should definitely be configurable. I will address this issue soon.
