### ISSUE TITLE
Task Flow\CreateDirectories does not work anymore

### ISSUE THREAD

**Issue by liwo** [TYPO3/Surf#25]
The Task tries to create directories shared/Data/Logs, shared/Data/Persistent and shared/Configuration, but with change 642f7c30b05f29cb457c84fa5960633c34ab8456 the base directory for creating these directories changed from the deployment base to the release directory. 

I could not find a specific reason for mentioned change, should we fix the Flow task or revert said change?

**Comment by kaystrobach** [comment]
@helhum as the mergerequest was merged this issue should be closed - right?

**Comment by helhum** [comment]
Yeah, thanks
