### ISSUE TITLE
Simplify composer autoloader optimization

### ISSUE THREAD

**Issue by Sebobo** [TYPO3/Surf#252]
It's possible to optimize the composer autoloader during composer install.
This can improve application response times as the file system checks are skipped. See https://getcomposer.org/doc/articles/autoloader-optimization.md for details.

As file system checks are disabled, this should only be done for production environments where nobody is working on the files by hand. Therefore making it default is dangerous.

Currently this can be activated for example by adding the following configuration when using the 

        $deployment->getWorkflow()
            ->setTaskOptions('TYPO3\\Surf\\DefinedTask\\Composer\\LocalInstallTask', [
                'additionalArguments' => ['--optimize-autoloader']
             ]
        )

In my opinion this should be easier to configure either by providing a really good documentation (with the danger that people don't spot it) or by providing a shortcut option. Maybe we could create a `useful options for composer installations` or add a php application example chapter.

One tricky thing is that it doesn't work when setting the option for the `InstallTask` as the BaseApplication creates a defined task called `LocalInstallTask` (which is based on `InstallTask`) which needs the option.

Any other ideas?

**Comment by t3easy** [comment]
https://github.com/TYPO3/Surf/blob/master/src/Task/Composer/InstallTask.php#L48
> --classmap-authoritative (-a): Autoload classes from the classmap only. Implicitly enables --optimize-autoloader.
