### ISSUE TITLE
Describe doesn't show tasks added to all applications

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#259]
## Expected Behavior
All tasks that are executed are visible via describe

## Actual Behavior
Tasks added to _all_  applications are not visible via describe before/after tasks that are added to an single application (which are all default tasks)

## Steps to Reproduce the Problem

  1. Add a task to all applications (don't pass the $app to before/afterTask)
      ```
      $deployment->getWorkflow()
                ->beforeTask(\TYPO3\Surf\Task\TYPO3\CMS\SetUpExtensionsTask::class, 
      \TYPO3\Surf\Task\TYPO3\CMS\CompareDatabaseTask::class)
      ```
  1. run surf descibe project
  1. You won't see the CompareDatabaseTask

related to #134 #151
## Specifications

  - Surf Version: master
  - Application: TYPO3 CMS
  - PHP Version: 7.2
  - Platform:
  - Environment (CI):
  - Deployment configuration:

**Comment by simonschaufi** [comment]
Adding a task with `addTask` works fine, it's just that it doesn't work with before and after.

**Comment by t3easy** [comment]
Found the problem.

**Comment by t3easy** [comment]
See: https://github.com/TYPO3/Surf/commit/afb0a58c1b1b895c1dc07231518f4f62f4af4e5d
If you add a task to all apps and then add a 2nd task before or after that one to just one app it is missing. Also if you add a task to just one app and add a 2nd task before or after all apps.
Problem is that we only look at before/after task in the same app:
https://github.com/TYPO3/Surf/blob/master/src/Command/DescribeCommand.php#L186
We have to output $applicationName and '_'(all).
