### ISSUE TITLE
Can't install Flow 5 along with Surf 2.0.0-beta11

### ISSUE THREAD

**Issue by cymn14** [TYPO3/Surf#263]
## Expected Behavior
Composer should be able to install both Flow ^5.0 and Surf 2.0.0-beta11

## Actual Behavior
There's a conflict. Flow 5 requires neos/utility-files ~5.0.0 and Surf 2.0.0-beta11 requires neos/utility-files ^3.0.

## Steps to Reproduce the Problem

  1. add "neos/flow": "^5.0" to "require" section of composer.json
  2. add "typo3/surf": "2.0.0-beta11" to "require" section of composer.json
  3. run composer install / update

## Specifications

  - Surf Version: 2.0.0-beta11
  - PHP Version: 7.1

**Comment by t3easy** [comment]
It is not recommended and often not possible to install surf to the same composer project as your app. Please install surf to a separate project or use the phar distribution. Please see https://docs.typo3.org/surf/Installation/Index.html for more details.

**Comment by sabbelasichon** [comment]
@cymn14 Please use the phar-File instead. I am going to close this issue.

**Comment by kaystrobach** [comment]
Maybe we can add a surf.phar composer repo only containing the phar file. 

Or add the phar to https://phar.io/
