### ISSUE TITLE
Simulate WebOpcacheResetCreateScriptTask and WebOpcacheResetExecuteTask fails

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#291]
## Expected Behavior
Be able to simulate a deployment with WebOpcacheResetCreateScriptTask and WebOpcacheResetExecuteTask tasks.

## Actual Behavior
Simulate fails because of exeption

```
TYPO3\Surf\Task\Php\WebOpcacheResetExecuteTask
Got exception "The required option "scriptIdentifier" is missing." rolling back.
```

## Steps to Reproduce the Problem

  1. deployment with both tasks
  1. surf simulate deployment
  1. get exception

## Specifications

  - Surf Version: dev-master
  - Application: TYPO3 CMS
  - PHP Version: 7.2
  - Platform: 
  - Environment (CI): GitLabCI
  - Deployment configuration:

**Comment by simonschaufi** [comment]
scriptIdentifier is a required parameter, therefor this is ok. If I set the parameter, everything works fine.
