### ISSUE TITLE
active maintainer, could you please reach out to TYPO3 GmbH concerning automated documentation rendering

### ISSUE THREAD

**Issue by maddy2101** [TYPO3/Surf#296]
Hello dear maintainer,

currently the documentation is under overhaul, and this affects the automated documentation rendering, when this repository receives patches or tags.

It would be awesome, if one of you could contact me (anja.leichsenring@typo3.com) asap, so we can align on what will change and how the Surf documentation is affected.

Thanks a bunch
Anja

**Comment by kaystrobach** [comment]
is there a documentation about the changes?

**Comment by t3easy** [comment]
I've written with Anja. 
Summarized:
No technical change for Surf right now. The generation of the docs will happen on Bamboo soon, and we have to ping them if we need to build other doc releases then 2.0.0-beta11 or master.
After the new doc build infra is up and running smooth, we could maybe implement an automated process, e.g. call a webhook with Travis. But as we don’t have that much releases, we go for the manual process to change which tags have to be rendered.

Thanks Anja!
