### ISSUE TITLE
Add Task to check remote platform reqs

### ISSUE THREAD

**Issue by kaystrobach** [TYPO3/Surf#299]
## Expected Behavior

initial discussion: https://github.com/TYPO3/Surf/pull/298

@t3easy **should**  we had it last week, that our ddev env was correctly configured and an admin removed just one php extension, which broke the whole system ... so it might be helpfull in the future.

`composer check-platform-reqs`

and it's just one command at the first glance.

The solution should take care of transfering a composer.phar to the target system and execute the check there. Running the checks only locally is not the goal.

## Actual Behavior

no check or local checl

## Steps to Reproduce the Problem

  1. define a platform requirement in your composer.json
  1. deploy to a system not fullfilling that requirement

**Comment by sabbelasichon** [comment]
@kaystrobach Thanks for the suggestion, but i am against the idea transferring a composer.phar to the remote system. This should not be the responsibility of Surf.
