### ISSUE TITLE
Document migration path from Flow package version to standalone version

### ISSUE THREAD

**Issue by helhum** [TYPO3/Surf#3]
Most notably:
- Use command to migrate deployment definitions
- Move deployment definitions to ~/.surf/
- Default deployment strategy changed from remote git to rsync

**Comment by kaystrobach** [comment]
use ` --configurationPath=Build/Surf` if you do not want to move any file 😄

**Comment by sabbelasichon** [comment]
This is part of the documentation issue. This issue can be closed.
