### ISSUE TITLE
phpBinaryPathAndFilename ignored for Neos/Flow CLI tool

### ISSUE THREAD

**Issue by christian-fries** [TYPO3/Surf#303]
## Expected Behavior
Surf should use the defined `phpBinaryPathAndFilename` to execute Neos/Flow CLI commands (`./flow`)

## Actual Behavior
The default php version of the node is used.

## Specifications

  - Surf Version: 2.0.0-beta8
  - Application: Neos Flow 4.3
  - PHP Version: 7.2

**Comment by martinlipp** [comment]
+1
But I'm guessing that this is not possible, since Surf has no access to the Settings.yaml files of Flow. It should be possible though, with a dedicated configuration option inside Surf.

**Comment by kaystrobach** [comment]
I think there is an env var for that, but better configure it via the settings. We somve that during the initial deployment.

**Comment by t3easy** [comment]
The idea is to use the same option like in TYPO3 deployments to call flow. https://github.com/TYPO3/Surf/blob/master/src/Task/TYPO3/CMS/AbstractCliTask.php#L56

**Comment by kaystrobach** [comment]
Mhmm would be possible, let me check that, that still needs the option to have that i the settings, as flow uses subprocesses to compile and for other stuff

**Comment by kaystrobach** [comment]
The setting can be reviewed here:

https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Configuration/Settings.Core.yaml

From my POV its ok to simply call the primary flow script with a php runtime like described for TYPO3. flow does check wether the 2 versions match

**Comment by martinlipp** [comment]
Changing the buildCommand() method in src/Application/Neos/Flow.php should do it:
https://gist.github.com/martinlipp/19cdbfd9ff8946e755db5ea0e72a8d16

**Comment by t3easy** [comment]
@martinlipp Would you like to send a PR?
