### ISSUE TITLE
What is missing for the next stable release?

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/Surf#308]
Surf is in beta for a really long time now. What is missing for the next stable release?

**Comment by t3easy** [comment]
Code cleanup, standardisation... time

**Comment by simonschaufi** [comment]
If you could be a bit more precise, I could help with code cleanup.

**Comment by YetiCGN** [comment]
Thank you for 2.0.0! It's really great to finally have a stable release.

I actually only noticed the release when in a legacy project, `dev-master` complained it needed PHP ^7.2 and the project still runs on PHP 7.0. 😄
