### ISSUE TITLE
Change default config for deployment of Flow/Neos apps 

### ISSUE THREAD

**Issue by Sebobo** [TYPO3/Surf#31]
The default setting for Flow is this:

```
protected $options = array(
    'packageMethod' => 'git',
    'transferMethod' => 'rsync',
    'updateMethod' => 'composer'
);
```

This would do a git checkout, then transfer the data to the server and then run composer install.
This means also that other post install tasks would run on the target node.

I would propose to change this back to the normal Application default like this:

```
protected $options = array(
    'packageMethod' => 'git',
    'transferMethod' => 'rsync',
    'updateMethod' => null
);
```

Because this would do a local git checkout, then run composer and then transfer everything to the target node and only create the release.

A problem is also that for example setting the `packageMethod` to `git` and leaving the `updateMethod` to `composer` would run `composer install` two times as the Flow app automatically adds the composer install task depending on those methods.

Looking into this also reveals for me that it's a bit difficult to understand from those options what actually happens...

**Comment by sabbelasichon** [comment]
Is this still valid?

**Comment by sabbelasichon** [comment]
@Sebobo And would this change introduce a BC break?

**Comment by Sebobo** [comment]
I think this would change the behavior for some.
Running composer install on the source only instead of the target might create different set of packages or cause issues.
But I think it makes sense to make the configuration more predictable and offer some pointers for people who upgrade to the final release.

**Comment by sabbelasichon** [comment]
Do not fully understand your last comment. Are you going to change it or do we leave it as it is? 
Would like to close more issues ;-)
