### ISSUE TITLE
Create documentation for every task

### ISSUE THREAD

**Issue by helhum** [TYPO3/Surf#33]
Every task should have a documentation block as class annotation

**Comment by dgrammlich** [comment]
Hi @helhum, I would take over this issue. :)

**Comment by helhum** [comment]
@dgrammlich \o/

Do you need anything for the start?

**Comment by dgrammlich** [comment]
@helhum I only need a quick feedback please. Let's see if I got it right - it's my first contribution _ever_. 
I made a clone from your repository, I made a branch. I go through the Tasks folder and give every Task class an annotation, if missing. When I don't understand the purpose of the Task, I'll ask you. When I'm done, I make a pull request from my branch to `master`. 
Did I miss something? =)

**Comment by helhum** [comment]
No, you did not miss something. That sounds awesome!  Thanks a bunch!

**Comment by dgrammlich** [comment]
@helhum Is a format like this okay? Or should I change something?
```php
/**
 * Tag a git repository and its submodules.
 *
 * It takes the following options:
 *
 * * tagName - The name of the tag
 * * description - The description for the tag
 * * recurseIntoSubmodules (optional) - If true, tag submodules as well
 * * submoduleTagNamePrefix (optional) - Prefix for the submodule tags
 *
 * Example:
 *  $workflow
 *      ->setTaskOptions('TYPO3\Surf\Task\Git\TagTask', [
 *                  'tagName' => 'earth2',
 *                  'description' => 'Another release to save the planet',
 *                  'recurseIntoSubmodules' => true,
 *                  'submoduleTagNamePrefix' => 'sub-'
 *              ]
 *          ]
 *      );
 */
```

**Comment by helhum** [comment]
@dgrammlich that format looks perfect to me. 
Thanks again!

Feel free to make documentation of each task an individual commit in your branch if you want to

**Comment by sabbelasichon** [comment]
For the documentation see also #93

**Comment by sabbelasichon** [comment]
@Sebobo or @kaystrobach 

We have almost every task described expect the ones for Neos and Flow.
Could one of you Add some phpdocs for these tasks? Would be awesome.

**Comment by kaystrobach** [comment]
working on it - will do a separate PR for it, as I can't write into @Sebobo s repo

**Comment by kaystrobach** [comment]
feel free to commend the PR.
