### ISSUE TITLE
Create code to documentation converter

### ISSUE THREAD

**Issue by helhum** [TYPO3/Surf#34]
Read class annotations from tasks and create documentation from that

**Comment by Sebobo** [comment]
@dgrammlich we could maybe use https://github.com/varspool/sphpdox to convert the PHPDoc to Sphinx/Rst converter and then automatically move it to readthedocs.

**Comment by helhum** [comment]
sounds great!

**Comment by dgrammlich** [comment]
I gave it a try and installed `sphpdox` with Composer. I had to downgrade `symfony/console` and `symfony/process` to the latest 3.0 version, maybe you can have a look at it.
The convertion to ReST worked fine. You can find the files in the `Documentation` folder.

**Comment by Sebobo** [comment]
Really cool :)

We should remember to exclude the documentation in the phar build.
Maybe this is already like that, but I didn't yet look into it.

I will also check what is needed for readthedocs, as I already set that up some time ago.

**Comment by dgrammlich** [comment]
@Sebobo I put the package to `require-dev` and made a pull request.

**Comment by sabbelasichon** [comment]
We are already doing it to create the documentation from Annotations -> ReST.
