### ISSUE TITLE
escapeshellarg breaks shellcommands

### ISSUE THREAD

**Issue by kaystrobach** [TYPO3/Surf#35]
given you have an deployment step like:

```
$workflow->defineTask(
	'sbs.lapo:fixHtaccess',
	'TYPO3\\Surf\\Task\\ShellTask',
	array(
		'command' => 'sed -i "s/RewriteBase \/.*/RewriteBase \/staging\/ \n SetEnv FLOW_CONTEXT Production /g" {releasePath}/Web/.htaccess'
	)
);
```

Then the escapeshellarg in https://github.com/TYPO3/Surf/blob/2.0.0-beta6/src/Task/ShellTask.php#L41 will break the command as the path is not concatenateable.

Even worse the replacement in the rollbakc step returns different data, as there is no escape ...
https://github.com/TYPO3/Surf/blob/2.0.0-beta6/src/Task/ShellTask.php#L87

**Comment by helhum** [comment]
> will break the command as the path is not concatenateable

What exactly does this mean? What is the final command that is being executed?

**Comment by kaystrobach** [comment]
given `releasePath = some/scary/path`

i could do `cd {releasePath}/some/sub/folder` in older surf releases, as it was executed exactly like you see it.

`cd some/scary/path/some/sub/folder`

Now the same command transforms into ``cd '{releasePath}'/some/sub/folder` (see the two added `'`)

`cd 'some/scary/path'/some/sub/folder`

this is done by `escapeshellarg`as described on php.net:

> escapeshellarg() adds single quotes around a string and quotes/escapes any existing single quotes allowing you to pass a string directly to a shell function and having it be treated as a single safe argument. This function should be used to escape individual arguments to shell functions coming from user input. The shell functions include exec(), system() and the backtick operator.
http://php.net/manual/en/function.escapeshellarg.php

As the last command is definitly invalid this will fail ...

My current workaround is a simple `cd {releasepath};` before each command, but this fails once i have to use more than one of the variables ...

**Comment by helhum** [comment]
> cd 'some/scary/path'/some/sub/folder

This is a perfectly valid command. The quotes do not harm at all. In contrary they make spaces in the path possible. What exactly is failing for you on? In what exact environment is it failing?

**Comment by kaystrobach** [comment]
i deployed to a debian server and the result was a path not found from the terminal

**Comment by helhum** [comment]
> i deployed to a debian server and the result was a path not found from the terminal

If you type `cd 'some/scary/path'/some/sub/folder` directly in the terminal, it does not work?

**Comment by helhum** [comment]
I'm really wondering what is going wrong on your side, as the above is just regular quoting. See e.g.: http://www.grymoire.com/Unix/Quote.html#toc-uh-8

**Comment by kaystrobach** [comment]
> Will test again and give some feedback soon
Thank you for your time.

Nyway non escaping in rollback step is then a bit inconsistent

**Comment by helhum** [comment]
> Nyway non escaping in rollback step is then a bit inconsistent

True. I consider not escaping a bug that needs to be fixed. There are more places where escaping does not happen currently

**Comment by kaystrobach** [comment]
atleast for me it's fixed now with a different syntax, i found the problem i used another php tool, which was not able to understand pathes like `'whatever/test'/otherpathsegment` using `cd`before solved it for me.

**Comment by helhum** [comment]
>  i found the problem i used another php tool, which was not able to understand pathes like 'whatever/test'/otherpathsegment

I would really like to understand what is going on on your side.

given this simple PHP script:

```php
<?php
var_dump($_SERVER['argv']);
```

And calling it with `php test.php '/sdfasdfsa'/sdfasdf` I get:

```
array(2) {
  [0] =>
  string(8) "test.php"
  [1] =>
  string(18) "/sdfasdfsa/sdfasdf"
```

See? No quotes any more.

You could do me a favor and post the exact failing configuration?

**Comment by helhum** [comment]
@kaystrobach ping

**Comment by kaystrobach** [comment]
not reproduceable anymore, let's close it for now - thanks
