### ISSUE TITLE
Clarify folder related options for TYPO3 CMS tasks

### ISSUE THREAD

**Issue by SomeBdyElse** [TYPO3/Surf#38]
Right now, there are two options concerning the folder structure of TYPO3 CMS projects. 
- applicationRootDirectory
- applicationWebDirectory

There is no reference to either of these options outside the TYPO3 CMS tasks scope. 

Right now, both options seem to be used inconsistently. 

Example:
- `SymlinkDataTask` symlinks `fileadmin` and `user_upload` in the `applicationRootDirectory`. This seems to indicate that `applicationRootDirectory` is the docroot.
- `AbstractCliTask->fileExists` looks for files relative to `applicationRootDirectory`, while `AbstractCliTask->directoryExists` looks for folders in `applicationWebDirectory`
- `FlushCachesTask` looks for the coreapi package in `{applicationRootDirectory}/{applicationWebDirectory}/typo3conf/ext/coreapi` but tries to execute the cli dispatcher in `{applicationRootDirectory}/typo3/cli_dispatch.sh` .

**Comment by SomeBdyElse** [comment]
To clarify the options we could
* Remove `applicationWebDirectory` and use `applicationRootDirectory` to point to the web folder. This requires the fewest changes. 
* Keep both options and adjust all TYPO3 CMS related tasks to respect them both. This requires adjustments to the `AbstractCliTask`, all coreapi related tasks and `SymlinkDataTask`.
* Remove both options and replace them with a new `webFolder` option. Introduce getters and setters on the TYPO3 CMS application class. Adjust all tasks to respect the new option. 

Neither of these options will work without a breaking change. 

It would be great to know if anyone uses the `applicationRootDirectory` option to point to anything but their `Web` folder. 

I personally tend to use the following folder structure. 

```
new-project <-- root directory
new-project/.git
new-project/composer.json
new-project/Web <-- web directory
new-project/Web/.htaccess
new-project/Web/typo3
```

**Comment by helhum** [comment]
> I personally tend to use the following folder structure.

Yes. This should be the default case. The following should also be supported:

```
new-project <-- checkout root
new-project/.git
new-project/app/ <-- application root directory
new-project/app/composer.json
new-project/app/web <-- application web directory
new-project/app/web/.htaccess
new-project/app/web/typo3
```

both root and web directory need to be specified relative to the checkout directory and it should be possible to configure them independendly. The latter means, that it can be possible that the application web directory is not a subdirectory of the application root directory

**Comment by helhum** [comment]
hm, while thinking a bit more about it, introducing something like `applicationRootDirectory` consistently, would mean touching almost any existing task.

Therefore I decided to go with option 3 (Remove both options and replace them with a new webDirectory option and introduce getters and setters on the TYPO3 CMS application class. Adjust all tasks to respect the new option
