### ISSUE TITLE
Incompatible --force option in FlushCachesTask with TYPO3 Console >= 6.2

### ISSUE THREAD

**Issue by abeutel** [TYPO3/Surf#396]
## Expected Behavior
FlushCachesTask clears cache

## Actual Behavior
FlushCachesTask fails w/ exception
```
[ Symfony\Component\Console\Exception\RuntimeException ]
The "--force" option does not exist.
cache:flush [--files-only]
```
due to hard-coded `--force` option.

## Steps to Reproduce the Problem

  1. Use `"helhum/typo3-console": "^6.2.0"` in project
  1. Start deployment
## Specifications

  - Surf Version: 2.0.2
  - Application: TYPO3 CMS
  - PHP Version: 7.2.x
  - Platform: Linux
  - Environment (CI): PHP 7.2
  - Deployment configuration: Default w/ FlushCachesTask

**Comment by simonschaufi** [comment]
See the discussion here: https://github.com/TYPO3/Surf/pull/392

**Comment by abeutel** [comment]
@simonschaufi I see. What about something like an application option used in `src/Task/TYPO3/CMS/FlushCachesTask.php` like:

```
return [
    $this->getConsoleScriptFileName($node, $application, $deployment, $options),
    'cache:flush',
    ($application->getOption('omitForceOptionOnCacheFlush') === true ? '' : '--force')
];
```

**Comment by t3easy** [comment]
I’m personally more a friend of positive settings. Maybe an option that sets `['--force']` as default for v2 branch and empty array for master but can always be overridden by the deployment.

**Comment by abeutel** [comment]
@t3easy Isn't it positive when it does not change the current state and defaults to `--force` which can be overridden? ;-)

**Comment by t3easy** [comment]
Omit isn’t positive 😉
And the proposed solution would allow to set `--files-only`

**Comment by abeutel** [comment]
Ah, got it! So we agree on »keep existing behaviour but allow override«.

**Comment by t3easy** [comment]
For 2.x yes, for master/3.x I would go for the new default.

**Comment by t3easy** [comment]
Here a quick workaround:

```php
<?php
// ...
$deployment
    ->addApplication($application)
    ->onInitialize(
        function () use ($deployment, $application) {
            $deployment->getWorkflow()
                // ...
                ->defineTask($flushCache = 'Vendor\\FlushCachesTask', \TYPO3\Surf\Task\TYPO3\CMS\RunCommandTask::class, [
                    'command' => 'cache:flush'
                ])
                ->afterStage('switch', $flushCache, $application)
                ->removeTask(\TYPO3\Surf\Task\TYPO3\CMS\FlushCachesTask::class, $application);
        }
    );
```

**Comment by fe-hicking** [comment]
Just some feedback: We've implemented the quick workaround, which works well in our setup - thanks for being on top of it.

Do I understand your decission is, the 2.0 branch will get an Option like "UseForceOnCache" which is set to "true" by default, and the deployment can set it to "false", if the integrator knows that his setup uses a recent TYPO3 Console version.

And the master branch uses the same option, but it is set to "false" by default, so an integrator would need to explicitly set it to "true" if an older TYPO3 Console version is used.

If so, are you yourself working on it, or would you want someone (hint...) to create a PR for both branches? ;)

**Comment by t3easy** [comment]
@fe-hicking 
See:
https://github.com/TYPO3/Surf/pull/397

**Comment by t3easy** [comment]
Yes 2.x branch should keep current behavior with an option to remove the `--force` parameter This will require a 2.1.0 release.
Master should have reliable standards for current software versions so no `--force` by default.
