### ISSUE TITLE
Configurable composerRootPath

### ISSUE THREAD

**Issue by fe-hicking** [TYPO3/Surf#398]
We have several projects where our GIT repositories do not contain the composer.json file in the root, but rather in a subdirectory - because of reasons (tm).

Until now we have created our own InstallTask that extends \TYPO3\Surf\Task\Composer\InstallTask.

Recent Surf and PHP Updates have created issues that required us to patch method signatures several times, so we were thinking if it would be feasible to accept a PR for the current AbstractInstallPath that simply adds an option to manually set the composer path:

```
        if ($options['composerJsonPath']) {
            $composerRootPath = $composerRootPath . '/' . $options['composerJsonPath'];
        }
```

Would you be willing to implement such a PR into the official release? If so, we'd happily create one.

(Thanks for your work on Surf, it is a pleasure to be able to use such a tool)

**Comment by simonschaufi** [comment]
Sure, please go ahead and create a PR but imho it should not just be for composer.json but generally for a base path of the website.

**Comment by fe-hicking** [comment]
I've just added these two PRs (for master and 2.0 - I am not proficient enough to know if I could create one PR containing changes to multiple branches; feel free to ignore whatever is irrelevant).

I tried to make the setting refer to the project root, not just the composerJsonPath (as it was called for us internally). However I didn't find another place in the code currently where the new option could be used, too.

Also, I didn't see any tests for the current behaviour of the task, so I couldn't enhance the test for checking this. If you can point me to examples on how it should be done, I can try to implement a test.

Let me know if there's more I can/should do.

**Comment by simonschaufi** [comment]
Made a new release that includes this feature. https://github.com/TYPO3/Surf/releases/tag/2.1.1
