### ISSUE TITLE
smoketest apache problems

### ISSUE THREAD

**Issue by Lemmork** [TYPO3/Surf#40]
I want to use the smoke test. Therefore I have to configure my Apache to use the /releases/next path.
Unfortunatly after a deployment the next-Path is deleted.
Therefore reloading apache will fail.
Is there a best practice for that?

**Comment by helhum** [comment]
A smoke test is meant to be done **before** the switch state. After the switch, the website is live and can be tested directly anyway.

Am I missing something?

**Comment by Lemmork** [comment]
but if I deploy changes, I will have smoke tests continously.
If I need to restart my apache in the meantime it will fail because of the missing next folder.

**Comment by helhum** [comment]
> but if I deploy changes, I will have smoke tests continously.

I don't really understand that sentence

> If I need to restart my apache in the meantime it will fail because of the missing next folder.

Ah, that is true. I'm not sure if you can configure apache (or any other webserver) to be less restrictive with that

**Comment by Lemmork** [comment]
No unfortunatly you can't configure apache less restrictive.
Is there a reason why the next symlink is deleted?

**Comment by helhum** [comment]
> Is there a reason why the next symlink is deleted?

where should it point to after the symlinks are switched? There is no next release then any more

**Comment by Lemmork** [comment]
In my workaround I point to current. But in fact only an empty folder would be sufficient for apache.
