### ISSUE TITLE
cannot remove './next': Is a directory

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/Surf#418]
## Expected Behavior

Deployment removes the next directory before creating a new folder

## Actual Behavior

TYPO3\Surf\Task\SymlinkReleaseTask
    > rm: cannot remove './next': Is a directory
Got exception "Command returned non-zero return code: 1" but rollback disabled. Stopping.

## Steps to Reproduce the Problem

  1. When I add a new domain, my webhoster automatically creates a folder with that name and adds an index.html in it.
  1. Execute the deployment

**Comment by t3easy** [comment]
I have some problems to remove folders during a deployment that where not created before.
