### ISSUE TITLE
ShellCommandService tries to unlink file that does not exist

### ISSUE THREAD

**Issue by christian-fries** [TYPO3/Surf#424]
## Expected Behavior
The `ShellCommandService` should delete the file `$passwordSshLoginScriptPathAndFilename` only if it exists.

## Actual Behavior
The `ShellCommandService` wants to delete the file `$passwordSshLoginScriptPathAndFilename` anyway which throws an error if it does not exist. 

This behavior was introduced with the commit [85d1d0b](https://github.com/TYPO3/Surf/commit/85d1d0ba5522e556fc5b99ebba5ce884aa7cb122#diff-f3d7ff9b3b419ebc758ad24f5f792260R116). On line 116, the variable `$passwordSshLoginScriptPathAndFilename` is declared as empty string, so the test `isset($passwordSshLoginScriptPathAndFilename)` on line 156 will always be true.

## Steps to Reproduce the Problem

  1. Update surf to 2.2.0
  1. Create a configuration like the one in the [docs](https://docs.typo3.org/other/typo3/surf/master/en-us/Examples/TYPO3/Index.html) (do not configure a password for the node, use public key authentication)
  1. Simulate or run the deployment

## Specifications

  - Surf Version: 2.2.0 (issue only in this version)
  - Application: TYPO3 CMS
  - PHP Version: 7.4.5
  - Platform: macOS 10.15.6

**Comment by christian-fries** [comment]
The actual commit (not the release commit) was:
[TASK] Add rector, its config, a CI job and process the project https://github.com/TYPO3/Surf/pull/423/commits/aae9bd6a9c9b92f45049674deae1d3607878d896 

Seems like rector introduced this bug.

**Comment by simonschaufi** [comment]
It looks like the variable should be initialized with null instead of an empty string. Can you please create a PR that fixes it?

**Comment by t3easy** [comment]
> The actual commit (not the release commit) was:
> 
> [TASK] Add rector, its config, a CI job and process the project https://github.com/TYPO3/Surf/pull/423/commits/aae9bd6a9c9b92f45049674deae1d3607878d896 
> 
> 
> 
> Seems like rector introduced this bug.

Was my fault, because I changed the types manuals to the ones they are later.
