### ISSUE TITLE
Add Webhook for Documentation Rendering

### ISSUE THREAD

**Issue by susannemoog** [TYPO3/Surf#441]
Hey,

the documentation rendering now allows rendering of the surf documentation with the same mechanisms as the "normal" TYPO3 documentation. To make use of this, please add the hook as defined here: https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingDocForExtension/Webhook.html#webhook

Thanks!

Susi

**Comment by sabbelasichon** [comment]
@susannemoog Thanks. Done
