### ISSUE TITLE
[FEATURE] Task for cache:warmup

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#448]
https://github.com/TYPO3/typo3/commit/4e25a5787e1215645df02beaf51878a5c7f4bb07

**Comment by simonschaufi** [comment]
When should this task be executed? Before or after symlink switch?

**Comment by t3easy** [comment]
V11 will also have cache:flush
https://github.com/TYPO3/typo3/commit/63a097048841d73bcc230ac78004256b6e964108

**Comment by simonschaufi** [comment]
My question still remains. We still need to call this command at some point...

**Comment by t3easy** [comment]
@simonschaufi I'm on vacation and only on the mobile. Just opened the issue to not forget about it...
