### ISSUE TITLE
symfony/console exception "Incorrectly nested style tag found."

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3/Surf#449]
## Expected Behavior
If a Surf command produces output, it should be shown on the console. 

Sidenote: The conditions for Surf to show output are as far as I know:

Either of
* command exits unsuccessful
* command outputs something to `stderr`
* `surf` is run with `-v`

## Actual Behavior
If the output contains style tags or parts of it `symfony/console` tries to interpret them and might throw a `\Symfony\Component\Console\Exception\InvalidArgumentException('Incorrectly nested style tag found.')`.

That exception triggers a depoyment rollback.

## Steps to Reproduce the Problem

The actual use case was displaying some HTML in a smoke test. 

This simple task reproduces what happened:

```yaml
$deployment->getWorkflow()
  ->defineTask(
      'TestSymfonyTask',
      LocalShellTask::class,
      [
          'command' => [
              'echo "123</info>"',
          ],
      ]
  )
```

## Specifications

  - Surf Version: 2.3.2
  - Application: 
  - PHP Version: 7.4
  - Platform: Linux
  - Environment (CI): ddev
  - Deployment configuration:

**Comment by sabbelasichon** [comment]
I am going to close this issue due to inactivity. Just by reading i would guess this has nothing to do with Surf but with Symfony Console.
