### ISSUE TITLE
Deployment of TYPO3 11.5 with TYPO3 Console 7.0 and option "extensionKeys" exits with error

### ISSUE THREAD

**Issue by mz-aimcom** [TYPO3/Surf#450]
## Expected Behavior

`$deployment->setOption('extensionKeys', ['extension_key_1', 'extension_key_2']);`

Should lead to a call of `extension:setup` with parameters `-e extension_key_1` and `-e extension_key_2`.

## Actual Behavior

An Error occurs:
> No arguments expected for "extension:setup" command, got "extension_key_1,extension_key_2"

## Steps to Reproduce the Problem

  1. Set at least one extension key for option "extensionKeys"
  2. Run deployment
  3. `SetUpExtensionsTask` throws error

## Specifications

  - Surf Version: 2.3.2
  - Application: TYPO3 11.5.3
  - PHP Version: 7.4.3
  - Platform: Ubuntu 20.04.3
  - Environment (CI): -
  - Deployment configuration:
    Deployment of a composer based TYPO3 11.5 from a git repository to a docker container on a remote server.
    
    Deployment options:
    - `port`: `XXXXX`
    - `username`: `'YYYYY'`
    - `projectName`: `'ZZZZZ'`
    - `repositoryUrl`: `'ssh://ab@cd.ef/ZZZZZ.git'`
    - `branch`: `'release/*'`
    - `keepReleases`: `5`
    - `rsyncExcludes`: `['.git']`);
    - `transferMethod`: `'git'`
    - `packageMethod`: `null`
    - `updateMethod`: `null`
    - `extensionKeys`: `['extension_key_1', 'extension_key_2']`
    
    Task order:
    - `TYPO3\Surf\Task\CreateDirectoriesTask`
    - `TYPO3\Surf\Task\LockDeploymentTask`
    - `TYPO3\Surf\Task\GitCheckoutTask`
    - `TYPO3\Surf\Task\Generic\CreateSymlinksTask`
    - `TYPO3\Surf\Task\TYPO3\CMS\SymlinkDataTask`
    - `composer`
    - `yarn`
    - `gulp`
    - `TYPO3\Surf\Task\TYPO3\CMS\CompareDatabaseTask`
    - `TYPO3\Surf\Task\TYPO3\CMS\SetUpExtensionsTask`

**Comment by mz-aimcom** [comment]
Fixed in `master` branch by pull request #452.

**Comment by sabbelasichon** [comment]
Resolved by #460
