### ISSUE TITLE
Reimport static SQL data from extensions

### ISSUE THREAD

**Issue by mschwemer** [TYPO3/Surf#51]
While activating an TYPO3 CMS extension the static sql data is imported. Some extension rely on reimporting this data with up to date contents. Probably the best known example is "static_info_tables" and its language specific brothers and sisters. "static_info_tables" comes with an update script, which rewrites the table contents.

IMO it is necessary that those updates can be done automatically while a deployment.

Basically there are two options:

**1) New feature for TYPO3 core and extension configuration**

If an extensions is activated for the first time, the static sql data is imported into the database and a value is set in the table "sys_registry", that the import happened. If it is set to "1", the table is not touched any more. 

An option for the core could be, that the extension author defines whether the static data should be updated or not, when updating the extension.

**2) Surf & typo3_console**

A more simpler and faster to achieve solution might be to make it configurable for developers / integrators using surf and the typo3console.

The extensions that must / will have their static sql data reimported, could be defined in an array or a comma separated list in the options of surf. The import itself is done via typo3_console and the TYPO3 core InstallUtility and its functions "processDatabaseUpdates" or "importStaticSqlFile".

My favorite would be no. 2 as it would enable the feature for existing TYPO3 versions. But no. 1 would be the cleaner way.
 
What do you think?

Ciao
Marcus

**Comment by helhum** [comment]
I think Surf is the wrong place to discuss this. There is however an open pull request for typo3_console https://github.com/TYPO3-Console/typo3_console/pull/288

The complicated thing is, to get the functionality right conceptually and for that, I think there is no way around starting with the core itself. It does not make sense to overwrite every piece of functionality with typo3_console just to work around core issues (this is done too much already)

I close this here in favor of the pull request mentioned
