### ISSUE TITLE
Shell Task option expansion should also work for LocalShellTask

### ISSUE THREAD

**Issue by helhum** [TYPO3/Surf#55]
https://github.com/TYPO3/Surf/blob/9eef93038f5300c5d39c02a205c8015dd0271e9f/README.md#shell-task-option-expansion

Add 
- deploymentPath
- releasePath
- sharedPath
- currentPath
- previousPath

**Comment by sabbelasichon** [comment]
If you like i could takeover this task. Actually i already did it and could open a pull request.
Don´t know if you agree with my concept of inheritance. But at least i already fixed a bug thanks to create tests for both classes.

**Comment by helhum** [comment]
> If you like i could takeover this task. Actually i already did it and could open a pull request.

Perfect!

> Don´t know if you agree with my concept of inheritance.

Please don't do any inheritance, but rather copy the code. or put that code into one standalone object and use composition to add this shared functionality to the places where needed.

> But at least i already fixed a bug thanks to create tests for both classes.

Test are good. If you use composition tests for the individual objects are also easier to write


Thanks!
