### ISSUE TITLE
Enable asking for sudo password

### ISSUE THREAD

**Issue by TheLalaMan** [TYPO3/Surf#56]
As of now, Surf does not support asking for the sudo password during deployment. However, sometimes it is necessary during deployment (depending on your server infrastrukture / security considerations etc.) to execute a **sudo** command.

It would really be great to have this feature, not least because Surf's "bigger brother" Capistrano also supports it.

**Comment by helhum** [comment]
I have no plans or capacity to implement such a feature, this is why I close this issue.

Taken from http://stackoverflow.com/questions/18939784/how-to-run-commands-which-require-sudo-using-capistrano-v3 and http://capistranorb.com/documentation/getting-started/authentication-and-authorisation/ Capistrano v3 recommends to set passwordless sudo, which I would recommend for Surf as well.

So the might not have implemented this feature into the new version for good reasons.
