### ISSUE TITLE
typo3/surf files in wrong/strange location?

### ISSUE THREAD

**Issue by p34ch** [TYPO3/Surf#58]
Not sure if I'm really right here! (sorry)

Im just trying to get typo3/surf working with my neos site for many hours now. When I fire "composer require typo3/surf:dev-master" on the console at my neos instances root directory the packages content gets installed to Packages/Libraries/typo3/surf

Because of this no ./flow surf:* commands are available on the cli. What's the matter here? Could please anybody either provide some help or point me to the correct place where I may get help?

Thank you guys very much!

_(Below is a screenshot where the typo3/surf files are located after composer require command)_
![here is typo_surf](https://cloud.githubusercontent.com/assets/19345044/21130418/9295d276-c108-11e6-9af8-64338ba31201.png)

**Comment by helhum** [comment]
> Because of this no ./flow surf:* commands are available on the cli. What's the matter here?

The new version of Surf does not have *any* flow commands. It comes with its own symfony console commands. The easiest way to use it, is to [download the phar](https://github.com/TYPO3/Surf/releases/download/2.0.0-beta7/surf.phar) and use it as standalone tool
