### ISSUE TITLE
Move TYPO3 CMS Configuration to "typo3conf" instead of "Configuration"

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#61]
The TYPO3\\Surf\\Task\\TYPO3\\CMS\\CopyConfigurationTask switches the extension from .yml to .php but doesn't change the target path.

**Comment by helhum** [comment]
that is true, but what is the benefit of changing that?

**Comment by t3easy** [comment]
I would expect, w/o reading the Code or Doc, that files from .surf/Configuration/Deployment are copied over to webdir/typo3conf in context of a TYPO3 application.
Also this would facilitate the migration of other deployment solutions to surf.

**Comment by helhum** [comment]
I wouldn't do that. TYPO3 has no concept of layered configuration files, thus it has to be implemented on top with some conventions. That was the idea of this task and introducing a new directory which is **on purpose** different to `typo3conf` to make clear it is nothing that is supported by TYPO3 out of the box.

Meanwhile I had better ideas how to work with environment specific configuration, so this task is kind of obsolete, but stays for backwards compatibility.

If you have other uses for this task, I'm fine accepting a PR which makes the folder name configurable, but the default should stay (for 2.0.0)

**Comment by t3easy** [comment]
Sounds good to me. I know you have an other solution with .env, but I think for an smother migration this would make sense.

**Comment by sabbelasichon** [comment]
Mark as deprecated. Remove in version 3.0.0
