### ISSUE TITLE
Be able to use docker container as composerCommandPath 

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#63]
I don't have PHP 7 installed local and I don't want to fake composer platform with
`"config": {
	"platform": {
		"php": "7.0"
	}
}`
so I use docker
e.g. `docker run --name composer -v $(pwd):/app t3easy/composer:alpine install`

If i set this as composerCommandPath the `$(pwd)` will be escaped as it should be.

What about using some $replacePaths for composerCommandPath like in shell task especially for $manifestPath to do something like
`$composerCommandPath = 'docker run --name composer -v {manifestPath}:/app t3easy/composer:alpine'`

**Comment by sabbelasichon** [comment]
Closed: Due to inactivity. Feel free to reopen the issue.
