### ISSUE TITLE
TYPO3 CMS uses initialDeployment from $deployment

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#67]
TYPO3 CMS uses the option initialDeployment directly from the deployment
https://github.com/TYPO3/Surf/blob/master/src/Application/TYPO3/CMS.php#L69
It's better to use the option from the combined inherited option array.
This way it's not possible to add applications to the stack that use the same option:
```
$deployment->setOption('initialDeployment', false);
/** var \TYPO3\Surf\Application\TYPO3\CMS $typo3 */
$typo3->setOption('initialDeployment', true);
/** var \What\Ever\Application $app */
$app->setOption('initialDeployment', false); // or inherit from deployment
```

**Comment by sabbelasichon** [comment]
Would this be a BC break? Or could we implement it with BC in mind?

**Comment by sabbelasichon** [comment]
Closed: Due to inactivity.
