### ISSUE TITLE
Run composer pre-deploy scripts automatically 

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#68]
Scripts inside the scripts > pre-deploy array should run automatically.
https://github.com/helhum/TYPO3-Distribution/blob/master/composer.json#L49
This could be used to trigger e.g. npm to build an application inside a clean environment.
The post-install-cmd that is triggered by composer automatically, could hold other tasks.
A use case:
```
"scripts": {
	"post-install-cmd": [
		"# composer install composer.lock file present",
		"cd web/typo3conf/ext/sitepackage && npm install && gulp build"
	],
	"post-update-cmd": [
		"# composer update or composer install composer.lock NOT file present",
		"cd web/typo3conf/ext/sitepackage && npm install && gulp build"
	],
	"pre-deploy": [
		"cd web/typo3conf/ext/sitepackage && npm prune --production"
	]
},
```

The additional `npm prune --production` command deletes all devDependencies (necessary for the build) which are not necessary on production and should not be transferred to the remote node but keeps the normal production dependencies.
https://docs.npmjs.com/cli/prune

**Comment by t3easy** [comment]
I would like to develop that feature. Which triggers are useful? Should we prefix the script names with `surf-`?

- surf-pre-install-cmd
- surf-post-install-cmd
- surf-pre-deploy-cmd

**Comment by sabbelasichon** [comment]
Closed: Due to inactivity. Feel free to reopen the issue.
