### ISSUE TITLE
Add "initialize" command for deployment

### ISSUE THREAD

**Issue by helhum** [TYPO3/Surf#7]
Create a new workflow for initializing a deployment on remote nodes. This workflow should:
- Create deployment path (try `mkdir -p`) if it does not exist yet
- Create all needed directories (or at least clear cache if existing)
- Ask to create node specific environment files
- Optionally move data (assets, db) to nodes

**Comment by sabbelasichon** [comment]
I am going to close this issue. If you have any technical solution feel free to reopen it.
