### ISSUE TITLE
[FEATURE] Test all used tools during simulate

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#70]
A simulation of the deployment should test all tools that are used during deployment.
Maybe with the tools `which` and `where.exe` and there last return code.
This doesn't check the version or parameters but would be a first step.
The registration of that tools should be next to the command in the task.
e.g. something like
`$this->addToSimulatedTools('readlink');`
Next to https://github.com/TYPO3/Surf/blob/master/src/Task/CleanupReleasesTask.php#L50

A 2nd parameter for addToSimulatedTools could be a test command, if `which` won't fit.

**Comment by sabbelasichon** [comment]
Feel free to reopen.
