### ISSUE TITLE
Commands using 'typo3/cli_dispatch.phpsh' should take webDirectory into account

### ISSUE THREAD

**Issue by jacobsenj** [TYPO3/Surf#73]
Current tasks running 'typo3/cli_dispatch.phpsh' will fail because they get executed in the project root directory instead of the webDirectory (if that is in use, of course).

i.e. https://github.com/TYPO3/Surf/blob/master/src/Task/TYPO3/CMS/FlushCachesTask.php#L59 will fail if caches should be cleared using coreapi.

**Comment by helhum** [comment]
good catch. can you create a pull request for this?

**Comment by jacobsenj** [comment]
Sure, I can try to do it

**Comment by sabbelasichon** [comment]
@jacobsenj Is this still valid for you and did you try to fix it?
