### ISSUE TITLE
surf as global composer package does not find typo3cms package

### ISSUE THREAD

**Issue by koehnlein** [TYPO3/Surf#733]
## Expected Behavior

I install surf as global composer packages to not have dependency conflicts with my project. This should work like in 3.3.5

## Actual Behavior

The latest surf version cannot find `helhum/typo3-console` anymore. And the deployment fails with the message:

> Got exception "Package "helhum/typo3-console" is not installed" rolling back.

![surf-staging-88658-·-Jobs-·-ifa-TW313169_ifa_relaunch_typo3-·-GitLab](https://user-images.githubusercontent.com/16088567/229451293-b223f3cc-1310-4b57-a973-dd619e91a806.png)

It looks like it is only searched in global composer context. But I only have installed it in my project context.

![Annotate-a-local-image](https://user-images.githubusercontent.com/16088567/229452848-5ecd6e91-c7cb-4813-99ee-07f4c3862c09.png)

Maybe the problem is related to this change: https://github.com/TYPO3/Surf/commit/ef548c4013ac214875d49717919a6f2695281dd7#diff-4a022af7e0710b87f00f93c49d8aed34a09dd3b98ce7dd2517deaa2f7a6c879bR54

## Steps to Reproduce the Problem

  1. Install surf globally `composer global req typo3/surf:^3`
  2. Go to your project `cd <project>`
  3. Start deployment `~/.composer/vendor/bin/surf deploy`

## Specifications

  - Surf Version: 3.3.7, 3.3.8, 3.3.9
  - Application: TYPO3 
  - PHP Version:
  - Platform:
  - Environment (CI):
  - Deployment configuration:

**Comment by sabbelasichon** [comment]
@koehnlein Thanks. Can you check if it works with 3.3.10 again. I have also add an option to explicitly define the version of the used console. The option is named scriptFileVersion

**Comment by koehnlein** [comment]
@sabbelasichon Sorry, but now I have new error with 3.3.10 😢

```
example.com (TYPO3 CMS) TYPO3\Surf\Task\TYPO3\CMS\SetUpExtensionsTask
$example.com: "test -f '/usr/home/whatever/releases/20230404111235/vendor/bin/typo3cms'"
$example.com: "cd '/usr/home/whatever/releases/20230404111235' && TYPO3_CONTEXT='Production/Staging' /usr/bin/php81 'vendor/bin/typo3cms' 'extension:setupactive'"
    > 
    > [ Symfony\Component\Console\Exception\CommandNotFoundException ]     The command "extension:activate" does not exist.
```

**Comment by sabbelasichon** [comment]
If we cannot determine your console version automatically, you have to define it manually with the new option.

**Comment by koehnlein** [comment]
@sabbelasichon 7.1.2 in the currently tested project

> If we cannot determine your console version automatically, you have to define it manually with the new option.

Ok, we can do. But to be honest, I would not expect this type of change when updating from 3.3.5 to 3.3.10, regarding semantic versioning.

**Comment by sabbelasichon** [comment]
@koehnlein That was by no means intentional. Sorry, for the inconvenience. But before the change, someone was complaining that the way we try to guess what version of the Console you are using doesn´t work. So i have fixed one thing but broke another. What can i do about it? If you have a nice idea to make it perfect and clean, i would be happy to implement it.

**Comment by koehnlein** [comment]
One additional comment: Maybe it would be better to set the default value of `scriptFileValue` to `7.0.0` instead of `0.0.0`?

https://github.com/TYPO3/Surf/pull/734/files#diff-4a022af7e0710b87f00f93c49d8aed34a09dd3b98ce7dd2517deaa2f7a6c879bR80

It always was required to have at least version 7.0.0 of the TYPO3 console. So maybe this tiny modification would help more configurations to not break?

**Comment by sabbelasichon** [comment]
@koehnlein Thanks for your kind words. I am not upset and can also understand the frustration. I think we are going to release a new Major Version soon. Only supporting PHP >= 8.0. Removing some old tasks. Breaking things will be expected ;-)

**Comment by sabbelasichon** [comment]
> One additional comment: Maybe it would be better to set the default value of `scriptFileValue` to `7.0.0` instead of `0.0.0`?
> 
> https://github.com/TYPO3/Surf/pull/734/files#diff-4a022af7e0710b87f00f93c49d8aed34a09dd3b98ce7dd2517deaa2f7a6c879bR80
> 
> It always was required to have at least version 7.0.0 of the TYPO3 console. So maybe this tiny modification would help more configurations to not break?

Could be an option. But i fear that we break others deployments then.

**Comment by koehnlein** [comment]
@sabbelasichon Ok, one last idea: Show a warning that `scriptFileValue` must be set, if you detect `0.0.0`?
