### ISSUE TITLE
Not compatible with psr/log:^3 and maybe other problems with surf 3.4 as global composer package

### ISSUE THREAD

**Issue by koehnlein** [TYPO3/Surf#760]
## Expected Behavior

Surf 3.4 should work as global composer package

## Actual Behavior

I have installed surf as global composer package to not run into dependency conflicts with my TYPO3 installation. But with the newest surf version 3.4, all surf commands result in the same PHP error, even `surf --version`

> PHP Fatal error:  Declaration of TYPO3\Surf\Domain\Service\ShellCommandService::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void in /tmp/vendor/typo3/surf/src/Integration/LoggerAwareTrait.php on line 20

The problem seems the package "psr/log". When installing surf 3.3.x, "psr/log:^2" is installed, with surf 3.4, "psr/log:^3" is installed, because I do not have any other packages installed, that set any required "psr/log" version.

After locking "psr/log" to version ^2, the error disappears, but I see the next PHP error message:

> PHP Fatal error:  Cannot redeclare TYPO3\Surf\findAllReleases() (previously declared in /tmp/vendor/typo3/surf/src/functions.php:24) in /tmp/vendor/typo3/surf/src/functions.php on line 24

But I have absolute no idea, what's wrong here.

## Steps to Reproduce the Problem

  1. composer global req typo3/surf:^3.4
  2. surf --version

## Specifications

  - Surf Version: 3.4
  - Application: 
  - PHP Version: 8.2
  - Platform:
  - Environment (CI):
  - Deployment configuration:

**Comment by koehnlein** [comment]
> I would even keep it separate from your TYPO3 or any other app. It's a stand-alone app.

I have a container for deployment with pre-installed surf as only global composer package. So it is de facto stand-alone. Similar to https://github.com/t3easy/docker-surf/blob/main/Dockerfile#L30

**Comment by sabbelasichon** [comment]
@koehnlein The MR #770 should fix the issue. Could you try the latest release for me please.

**Comment by koehnlein** [comment]
@sabbelasichon Thanks. The psr/log problem is solved now.

I still run into the other problem

> PHP Fatal error: Cannot redeclare TYPO3\Surf\findAllReleases() (previously declared in /tmp/vendor/typo3/surf/src/functions.php:24) in /tmp/vendor/typo3/surf/src/functions.php on line 24

This seems to be a composer autoloading issue. I will open a new issue for that, if I could find out more.

**Comment by sabbelasichon** [comment]
I have run into the same issue yesterday and fixed it. I am going to publish a new release soon.

**Comment by sabbelasichon** [comment]
@koehnlein I have create another release 3.4.2. This should fix the last issue.

**Comment by koehnlein** [comment]
@sabbelasichon Thank you very much!
