### ISSUE TITLE
How to inject Logger in custom tasks?

### ISSUE THREAD

**Issue by jonaseberle** [TYPO3/Surf#777]
## Expected Behavior

When extending `TYPO3\Surf\Domain\Model\Task` (`abstract class Task implements LoggerAwareInterface {...}`), `$this->logger` is injected and can be used.

## Actual Behavior

For custom tasks, the 
```php
    $services->set(LoggerInterface::class)
        ->factory([service(LoggerFactory::class), 'createLogger']);
```
is not enabled thus the Logger is not injected.

I have patched Surf's `services.php` (in my case my custom tasks are in ./src on the same level as `composer.json`)

```diff
diff --git a/Resources/services.php b/Resources/services.php
--- a/Resources/services.php
+++ b/Resources/services.php
@@ -60,6 +60,8 @@
     $services->set(OutputInterface::class)
         ->factory([service(ConsoleOutputFactory::class), 'createOutput']);

+    $services->load('Custom\\', __DIR__ . '/../../../../src');
+
     $services->load('TYPO3\Surf\\', __DIR__ . '/../src')
         ->exclude([__DIR__ . '/../src/{Cli,Application,Exception,Domain/Model,Domain/Enum,DeprecationMessageFactory.php,Exception.php,functions.php}']);
```

I don't know how this could be solved for all custom tasks though in a way that does not rely on the specific path.

## Steps to Reproduce the Problem

  1. Create a custom task that uses `$this->logger->...`
  2. Add it to a workflow

## Specifications

  - Surf Version: 3.3.4+
  - Application: TYPO3
  - PHP Version:
  - Platform: Linux
  - Environment (CI): 
  - Deployment configuration:

Reference: https://docs.typo3.org/other/typo3/surf/main/en-us/Tasks/Index.html

**Comment by sabbelasichon** [comment]
@jonaseberle Good point. I have implemented the common LoggerAwareInterface check for custom task. If the task implements the interface the logger gets injected. This should do the trick, right?

**Comment by jonaseberle** [comment]
https://github.com/TYPO3/Surf/commit/5afa1ed6c8e7796807c843352808a60052af99bf looks good, thank you.
