### ISSUE TITLE
Wrong version information

### ISSUE THREAD

**Issue by jacobsenj** [TYPO3/Surf#780]
The surf.phar states an old version number after downloading the latest release (3.4.6).

## Expected Behavior

❯ ./surf.phar --version
TYPO3 Surf 3.4.6

## Actual Behavior

❯ ./surf.phar --version
TYPO3 Surf 3.4.3

## Steps to Reproduce the Problem

  1. wget https://github.com/TYPO3/Surf/releases/download/3.4.6/surf.phar
  1. chmod +x surf.phar
  1. ./surf.phar --version

## Specifications

  - Surf Version: Latest Release (currently 3.4.6)
  - PHP Version: 8.1
  - Platform: Darwin 22.6.0

**Comment by simonschaufi** [comment]
Will be fixed with the next release
