### ISSUE TITLE
Task to Dump the database of TYPO3 CMS before migration

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#80]
It would be helpful to have task that dumps the TYPO3 CMS database via typo3_console.
Per default this task should not be active to avoid problems with large DBs.

**Comment by sabbelasichon** [comment]
Could be very useful. Would like to create a pull request for that?

**Comment by kaystrobach** [comment]
Should we really cover all edgecases, where you can easily add this as shell task? IMHO this could be in the documentation...

**Comment by t3easy** [comment]
Thats a good question. But what are edge cases... E.g. for me #100, where you offered help, is not only an edge case, but also bad practice and shouldn't be supported OOTB...
Dumping the db with release identifier and cleanup is not just one shell task.

**Comment by kaystrobach** [comment]
#100 composer.lock removal might be interesting for integration tests, but how can you deploy in an defined way if the composer.json is removed?

**Comment by t3easy** [comment]
I've never said that I want to remove the composer.json!? Anyway the definition of edge case is vague.

**Comment by kaystrobach** [comment]
right it was the *.lock file ... and only in ticket #100 - so please do not feel offended.

agree that defining edgecases is relatively hard.

if we add a "backup" task we should also have a backup stage - right?  For copying files and folders, or do you want to do it in the deployment stage?

**Comment by sabbelasichon** [comment]
@t3easy Do you think this is still relevant? If so, i am going to create a Merge Request for it.

**Comment by t3easy** [comment]
IMO, a DB dump is helpful but not a backup of files as we don't change userspace files. An extension could have a update script that could modify userspace files but that's a lot `could`.
A backup stage is ok but not necessary, IMO.
One question is were to store the dump. On the remote server outside web root or on the system running surf.
With CI in mind, it would be great to dump to the system running surf e.g. inside the .surf folder. Then the dump could be configured as artifact and stored.
The universal [DumpDatabaseTask](https://github.com/TYPO3/Surf/blob/master/src/Task/DumpDatabaseTask.php) dumps one db directly to another db so it serves a different purpose.

**Comment by kaystrobach** [comment]
it only makes sense if the "backup" is transfered back to the maschine running surf

**Comment by sabbelasichon** [comment]
I am gonna close this issue.
