### ISSUE TITLE
Keep releases by age

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#81]
To continuously deploy small changes there should be a option to keep releases by age.

**Comment by sabbelasichon** [comment]
@t3easy Could please add some details what do you would expect how this can be configured? Can you keep the releases by seconds, minutes etc.?

I would suggest you can configure them only by seconds.

**Comment by kaystrobach** [comment]
How about having speaking Intervalls like ‘2 weeks or 2 days or 15 min‘

**Comment by kaystrobach** [comment]
See example 2 http://php.net/manual/de/function.date-parse.php
