### ISSUE TITLE
SymlinkDataTask directories should work like fileadmin and uploads

### ISSUE THREAD

**Issue by t3easy** [TYPO3/Surf#84]
I have a 2nd File Storage `downloads`
and placed the folder under `shared/Data/downloads` like `shared/Data/fileadmin`.
I set the option `directories` for the SymlinkDataTask 
`$application->setOption('TYPO3\\Surf\\Task\\TYPO3\\CMS\\SymlinkDataTask[directories]', ['downloads']);`

I would expect the symlink inside the web folder but it will be created in the root of the project.
```
composer.json
composer.lock
downloads -> ../../shared/Data/downloads
vendor
web
```

As a workaround I moved the data to `shared/Data/web/downloads` and set option to
`$application->setOption('TYPO3\\Surf\\Task\\TYPO3\\CMS\\SymlinkDataTask[directories]', ['web/downloads']);`

**Comment by helhum** [comment]
I think this behaviour is correct. it could be that I explicitly want the storage folder to not be in document root. but yes, maybe fileadmin should also be in `shared/Data/web/fileadmin`, but it also does not really matter, does it?

**Comment by t3easy** [comment]
I just wanted to note the inconsistent behavior. Keep as it is is one of the possible solutions.
