### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by DanielRuf** [TYPO3/Surf#92]
https://docs.typo3.org/surf/TYPO3SurfDocumentation/ from https://typo3.org/typo3-cms/additional-products/surf/

**Comment by marble** [comment]
For some time there has been documentation for different products at docs.typo3.org: neow, flow, surf, typo3. Later on it had been decided to only document the product TYPO3 CMS there.

**Comment by t3easy** [comment]
Thx for reporting.
AFAIK, everything that was in there is in now the Readme.md.
I close this for now, since the typo3.org page no longer exists and we're working on a new documentation.

**Comment by kaystrobach** [comment]
who is working on that - maybe you can give me the rights, so that i can connect read the docs?
