### ISSUE TITLE
Documentation regarding adding tasks seems to be incomplete/misleading

### ISSUE THREAD

**Issue by uris-dev** [TYPO3/Surf#93]
I tried to add and remove tasks following the documentation, but it didn't work.
 In the docs it is suggested to do
`$workflow = new \TYPO3\Surf\Domain\Model\SimpleWorkflow();`
to access the SimpleWorkflow object to add new tasks. However this obviously creates a complete new workflow, it does not allow you to modify the add tasks to the exiting one, as it seems to be implied in the docs.
To modify the existing workflow, it seems that you need to access the existing workflow with:
`$workflow = $deployment->getWorkflow();`
and it may be needed to be execute it in the onInitialize handler like:
````
$deployment->onInitialize(function () use ($deployment, $application) {
    // set file permission
    $workflow = $deployment->getWorkflow();
    // ...
}
````
If this is correct it would be helpful to update the documentation in this sense.

**Comment by sabbelasichon** [comment]
we will take this into account for the new documentation.

**Comment by Moongazer** [comment]
I think the [documentation](https://docs.typo3.org/other/typo3/surf/master/en-us/Tasks/Index.html#add-task-to-the-deployment-flow) is still misleading in the current version: if I try to add a workflow like described there, it will fail because `$workflow` is `NULL` before `onInitialize()`:
```
$deployment->addApplication($application);
$workflow = $deployment->getWorkflow(); // $workflow is NULL here

$deployment->onInitialize(function() use ($workflow, $application) {
   // $workflow seems to be only available after onInitialize(), if so, please update the docs
});
```

**Comment by t3easy** [comment]
@Moongazer Thank you for your feedback. Please check

- https://github.com/TYPO3/Surf/blob/task/prepare-release-2.2.0/Documentation/Tasks/Index.rst
- https://github.com/TYPO3/Surf/blob/task/prepare-release-2.2.0/Documentation/DeploymentFlow/Index.rst#manipulate-the-flow

if this meets your expectations.
