### ISSUE TITLE
Add rollback command task

### ISSUE THREAD

**Issue by simonschaufi** [TYPO3/Surf#96]
Currently there is no command for a rollback. The only rollback support is **during** deployment, but not afterwards. When the site is live, it's a pain to revert the symlinks by hand.

See Rollback in deployer: https://github.com/deployphp/deployer/blob/master/recipe/deploy/rollback.php

**Comment by t3easy** [comment]
Thats hard to automate because of database changes.
If you've changed the DB with the last deployment, your previous deployment could be in a broken state by just switching the symlink and flush caches.
What you can do is `git revert` and redeploy.

**Comment by helhum** [comment]
deployments not necessarily change the database. having a command that indeed just switches the symlink to previous deploy could be a nice addition. deployer has such command. but yes, priority shouldn't that high…

**Comment by t3easy** [comment]
As you say _not necessarily_. So maybe a warning with "press y to acknowledge" (and a force parameter) should be displayed before.

**Comment by simonschaufi** [comment]
Flow has up- and downmigrations. In that case they should also just be rolled back. Yes I'm aware that TYPO3 doesn't have that.

**Comment by tgaertner** [comment]
Actually if you made a db-dump during the deploy then it is possible to roll-back (with the downside to maybe lose some date if there was not a BE lock). Then we need the possibility to add custom tasks to the rollback process, not just switching the symlinks. With that in most cases a clean rollback would be possible.

**Comment by t3easy** [comment]
So we need some kind of RollbackWorkflow for each application, where you can hook in to add custom tasks...

**Comment by kaystrobach** [comment]
please postpone that to `2.(x+1)` where x is bigger than 1 ... so that we can have a stable release with docu first and then add new features ...
