### ISSUE TITLE
LocalInstallTask is triggered twice for Flow Apps

### ISSUE THREAD

**Issue by Sebobo** [TYPO3/Surf#97]
The `Flow` application registers it after the `package` stage and the `BaseApplication` after the `GitTask`.

**Comment by t3easy** [comment]
So which one to drop?
https://github.com/TYPO3/Surf/blob/master/src/Application/BaseApplication.php#L223
https://github.com/TYPO3/Surf/blob/master/src/Application/Neos/Flow.php#L81

**Comment by kaystrobach** [comment]
Please assign it to me - will check later

**Comment by kaystrobach** [comment]
after checking i would prefer removing:

https://github.com/TYPO3/Surf/blob/50179223ff456c742ba2c0ad347d87bf88ebfeaa/src/Application/Neos/Flow.php#L81

As this one is Package specific and does not make sense anymore ... IMHO the BaseTask should assume, that there is an composer.json and try to install all the dependencies ...

**Any objections?**

**Comment by t3easy** [comment]
Seems OK to me. But I'm not that familiar with Flow/Neos.

**Comment by kaystrobach** [comment]
ok, will test it and give feedback ... maybe i get it done next week during t3uxw

**Comment by kaystrobach** [comment]
add test for flow/neos via describe command
